# Generated by Django 3.2.9 on 2022-05-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietickets', '0002_alter_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
    ]
