# Generated by Django 3.2.9 on 2022-05-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietickets', '0003_remove_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
    ]
